spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  default-produces-media-type: application/json

backend:
  baseUrl: ${BASE_URL:http://localhost:8080/api}

jwt:
  secret-key: ${SECRET_KEY:bW9kZXJuc3VpdHBlcmhhcHNmaXJlcGxhY2ViYWxhbmNlY2VydGFpbmx5d2hlbnRhaWw=}
  access-token:
    expiration: 7776000000 # 3 meses


